
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery:8083/eureka

spring:
  application:
    name: first-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://uaa:8090/uaa/token_keys

logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG